# Generated by Django 5.1.5 on 2025-01-23 13:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pdfdocument",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "PDF文档",
                "verbose_name_plural": "PDF文档",
            },
        ),
        migrations.RemoveField(
            model_name="pdfdocument",
            name="uploaded_at",
        ),
        migrations.AddField(
            model_name="pdfdocument",
            name="chunk_count",
            field=models.IntegerField(default=0, verbose_name="文档块数量"),
        ),
        migrations.AddField(
            model_name="pdfdocument",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="创建时间",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pdfdocument",
            name="is_processed",
            field=models.BooleanField(default=False, verbose_name="是否已向量化处理"),
        ),
        migrations.AddField(
            model_name="pdfdocument",
            name="page_count",
            field=models.IntegerField(default=0, verbose_name="页面数量"),
        ),
        migrations.AddField(
            model_name="pdfdocument",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AddField(
            model_name="pdfdocument",
            name="vector_index_path",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="向量索引路径"
            ),
        ),
        migrations.AlterField(
            model_name="pdfdocument",
            name="file",
            field=models.FileField(upload_to="pdfs/", verbose_name="PDF文件"),
        ),
        migrations.AlterField(
            model_name="pdfdocument",
            name="title",
            field=models.CharField(max_length=255, verbose_name="文档标题"),
        ),
    ]
