# Generated by Django 5.1.5 on 2025-02-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_chatsession_user_pdfdocument_session_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdfdocument",
            name="document_type",
            field=models.CharField(
                choices=[("invatation", "招标书"), ("offer", "应标书")],
                default="invatation",
                max_length=20,
                verbose_name="文档类型",
            ),
        ),
    ]
