# Generated by Django 5.1.5 on 2025-03-28 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0003_pdfdocument_document_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("steps", models.JSONField(default=list)),
                ("task_plan", models.JSONField(blank=True, null=True)),
                ("tool_selection", models.JSONField(blank=True, null=True)),
                ("task_results", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_info",
                        to="chatbot.chatmessage",
                    ),
                ),
            ],
        ),
    ]
