# Generated by Django 5.1.5 on 2025-05-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_processinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processinfo',
            old_name='tool_selection',
            new_name='tool_selections',
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='id',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='chatmessage',
            table='chat_messages',
        ),
        migrations.AlterModelTable(
            name='chatsession',
            table='chat_sessions',
        ),
        migrations.AlterModelTable(
            name='processinfo',
            table='process_infos',
        ),
        migrations.DeleteModel(
            name='PDFDocument',
        ),
    ]
