# Generated by Django 5.1.5 on 2025-05-22 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_bio_user_interests'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users_user',
        ),
    ]
