# Generated by Django 5.1.5 on 2025-03-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_id", models.CharField(max_length=20, unique=True)),
                ("course_name", models.CharField(max_length=100)),
                ("instructor", models.CharField(max_length=50)),
                ("major", models.CharField(max_length=50)),
                ("semester", models.CharField(max_length=20)),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (1, "周一"),
                            (2, "周二"),
                            (3, "周三"),
                            (4, "周四"),
                            (5, "周五"),
                            (6, "周六"),
                            (7, "周日"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("classroom", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "academic_course",
                "ordering": ["day_of_week", "start_time"],
            },
        ),
    ]
