# Generated by Django 5.1.5 on 2025-03-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("club_id", models.CharField(max_length=20, unique=True)),
                ("club_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("president", models.CharField(max_length=50)),
                ("contact_email", models.EmailField(max_length=254)),
                ("member_count", models.IntegerField(default=0)),
                ("founded_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "活跃"),
                            ("inactive", "不活跃"),
                            ("disbanded", "已解散"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "academic_club",
                "ordering": ["club_name"],
            },
        ),
    ]
