# Generated by Django 5.1.5 on 2025-03-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0002_add_initial_clubs"),
        ("academic", "0002_club"),
    ]

    operations = []
